name: jenkins-example
director_uuid: 85152B21-EC66-4348-A5B7-D032E427925B

release:
  name: jenkins
  version: latest

compilation:
  workers: 1
  reuse_compilation_vms: true
  network: default
  cloud_properties:
   instance_type: m1.small

update:
  canaries: 1
  canary_watch_time: 3000-90000
  update_watch_time: 3000-90000
  max_in_flight: 1
  max_errors: 1

networks:

- name: default
  type: manual
  subnets:
  - reserved:
    - 10.0.0.2 - 10.0.0.10
    - 10.0.0.13 - 10.0.0.254
    range: 10.0.0.0/24
    gateway: 10.0.0.1
    static: 10.0.0.12
    dns:
    - 10.0.0.2
    cloud_properties:
      subnet: subnet-d4f8da92
      security_groups:
      - bosh

resource_pools:

- name: infrastructure
  network: default
  size: 1
  stemcell:
    name: bosh-aws-xen-ubuntu
    version: latest
  cloud_properties:
   instance_type: m1.small
jobs:

- name: jenkins
  template: jenkins_master
  instances: 1
  resource_pool: infrastructure
  persistent_disk: 24000
  networks:
   - name: default
     static_ips:
      - 10.0.0.12

properties:

  domain: pivotal.local
  description: Pivotal jenkins
  # Github credentials used by git plugin for http/https access
  github:
    username: 'admin'
    password: 'password'
  bosh:
    # BOSH micro IP available through ENV variable BOSH_MICRO_IP to Jenkins jobs
    micro_ip: '10.0.0.10'
  # S3 credentials used by the S3 plugin  
  amazon:
    accesskey: ''
    encrypted_secretkey: ''
    secretkey: ''
  jenkins:
    # Jenkins admin password for the web UI
    admin:
      password: admin
    # Jenkins plugins to auto install
    plugins:
      - copyartifact
      - locks-and-latches
      - git
      - greenballs
      - notification
      - depgraph-view
      - parameterized-trigger
      - s3

