---
golang/go1.1.2.linux-amd64-yacc-shaved.tar.gz:
  object_id: 5eb9144a-4182-4471-b82e-32df20fc102b
  sha: !binary |-
    MDJhYTlmNDdiOTVjZTAxMmI1NzAyZGFmNDFkM2ZmNGI3ODFhYzMwZQ==
  size: 41768327
git/git-1.7.11.2.tar.gz:
  object_id: 57004aac-0a43-43c2-8d7c-9e361d87925a
  sha: !binary |-
    ZjY3YjRmNmMwMjc3MjUwNDExYzY4NzJhZTdiOGE4NzJhZTExZDMxMw==
  size: 4015780
java/jdk1.7.0_45.gz:
  object_id: aeef9e6f-955a-42e2-8e21-8e63e9dba9a2
  sha: !binary |-
    MWM4Y2IyMjllMmY3ZjBhM2U1ZTc5OGEzMDA4YzVhMWY3YzYwNDkzNA==
  size: 138094686
java/jre-1.6.0_24-x86_64.tar.gz:
  object_id: bb1b448d-ef41-4cf8-9d55-bc48848382c3
  sha: !binary |-
    MDUxMWQ4MzNkZmQ5ODI1YTI2YzE4ZTlkNjg1ZGU2NGFjMDE1MWU4NQ==
  size: 34453414
jenkins/jenkins-1.509.2.war:
  object_id: abe36247-5dca-46c9-b8c7-78333e212dd8
  sha: !binary |-
    N2Q1OTVkZGQ4NTdmOTk5Yjc3MGIwZWMwMmI5YjBlODhjMGIyZTE3YQ==
  size: 53863401
libfontconfig/fontconfig-2.11.0.tar.gz:
  object_id: 2e38039e-df38-497d-9e87-44e4fabd15ec
  sha: !binary |-
    NjUwZjhmM2I4YzdiNmZhYzY4YzI1ZjM3OTYxNmI1YmU0OGJlMTNiZg==
  size: 1844487
libfreetype/freetype-2.5.0.1.tar.gz:
  object_id: b130dc30-ed62-436b-8166-7d6b5949304c
  sha: !binary |-
    MmQ1MzliMzc1Njg4NDY2YThlN2RjYzQyNjBhYjIxMDAzZmFhYjA4Yw==
  size: 2113872
libyaml/yaml-0.1.4.tar.gz:
  object_id: 1da8c8d3-b924-4ec7-8599-6ea37c7d564d
  sha: !binary |-
    ZTBlNWUwOTE5MmFiMTBhNjA3ZTNkYTI5NzBkYjQ5MjExOGY1NjBmMg==
  size: 471759
nginx/nginx-1.4.2.tar.gz:
  object_id: d2e5a6d7-0b1e-48bc-ac46-0adc4ec4d96e
  sha: !binary |-
    OGYwMDZkYzc3Mzg0MGI2NjI0YTEzN2E1ODRmZjg4NTBkNTE1NWUzZg==
  size: 767688
nginx/pcre-8.33.tar.gz:
  object_id: cfeb8ac8-1083-48cb-aa9e-b27118f2bfa9
  sha: !binary |-
    YmNlYWZiNTM1NTMyMTlkYWQyNTkzYmI4YWYwNmRhNGQwN2ZkMzgyOA==
  size: 1889401
phantomjs/phantomjs-1.9.2-linux-x86_64.tar.bz2:
  object_id: 002ca7c8-40f0-4802-9d98-44bcfa7b56ae
  sha: !binary |-
    Yzc4YzQwMzdkOThmYTg5M2U2NmZjNTE2MjE0NDk5YzU4MjI4ZDJmOQ==
  size: 13279068
ruby/bundler-1.3.5.gem:
  object_id: 6bea5085-1574-4139-9c41-2cd780bf9199
  sha: !binary |-
    MmNhZDMwNTJhNTliODNmMWY2MTZlODIwMmY1YzcxNGU0NmJkODUyMw==
  size: 268800
ruby/ruby-2.0.0-p247.tar.gz:
  object_id: ae04ed27-87f5-4c81-ad7e-205c71e607f7
  sha: !binary |-
    ODUwYjkzYWZiNTkxNGVlM2YzOGYwNzY5ZTMwOWFiZjBjZWRmMDg0Yg==
  size: 13652782
ruby/ruby-2.0.0-p353.tar.gz:
  object_id: fa7b4c67-31ba-48b3-8599-8bf2909149ca
  sha: !binary |-
    N2YyYzhiOGY1NjgyYWFiYzExMTRmNDRkMzZkMzE0YzZjMzdjMTFiOA==
  size: 13572794
ruby/rubygems-2.0.7.tgz:
  object_id: 61a911f9-2d85-48f5-ac20-0674e4867872
  sha: !binary |-
    ZjBiMGEwM2Q1NzNlMjExMjViYTVkYTFkYjE0NDYxZDZhOTkzNDBkNA==
  size: 337146
sqlite/sqlite-autoconf-3070500.tar.gz:
  object_id: 1f184193-bfa0-47d6-80f2-850d85de5718
  sha: !binary |-
    NGUxMzM4NDk3YjhkYTUwYjg0MzA3MTkxYmIzNDE4ZTllYzU3MTVkNw==
  size: 1551070
gcf/gcf-linux-amd64-12.2.14.tgz:
  object_id: 30e5e0e2-1711-4e45-a2d9-58b1b3f12d68
  sha: !binary |-
    NmQ1ZTc0MDU1ZmE5ZjMzMDlkNTE5ZjQxMDM3ZDUwYWE5ZDE3YWJlMQ==
  size: 3388453
